export const EVENTS = {
  DEBUG: "DEBUG",
  OPEN_WINDOW: {
    AUTH: "OPEN_WINDOW/AUTH",
    MAIN: "OPEN_WINDOW/MAIN",
    USER_ACCOUNT_MANAGER: "OPEN_WINDOW/USER_ACCOUNT_MANAGER",
  },
  CLOSE: "CLOSE",
}
