@startuml

interface BrowserWindow{}

interface Page {}

class AuthenticationWindow{}

class LoginPage{}

class RegisterPage{}

class MainWindow{}
class OuterAccountListPage{}
class UserAccountManagerWindow{}
class UserAccountListPage{}
class UserAccountSettingPage{}

BrowserWindow <|-- AuthenticationWindow
BrowserWindow <|-- MainWindow
BrowserWindow <|-- UserAccountManagerWindow
 LoginPage --|> Page
 RegisterPage --|> Page
 UserAccountListPage --|> Page
 UserAccountSettingPage --|> Page
 OuterAccountListPage --|> Page
AuthenticationWindow ..> LoginPage
AuthenticationWindow ..> RegisterPage
AuthenticationWindow .> MainWindow
MainWindow .> UserAccountManagerWindow
MainWindow ..> OuterAccountListPage
UserAccountManagerWindow ..> UserAccountListPage
UserAccountManagerWindow ..> UserAccountSettingPage

@enduml