@startuml ユースケースパッケージ

package アカウント管理{
    (アプリアカウントを作成できる)
    (アプリアカウントの認証情報を再設定できる)
    (ユーザーアカウントを作成できる)
    (ユーザーアカウントに共通鍵を再設定できる)
    (ユーザーアカウントのプロフィールを設定できる)
}

package 一般{
    (アプリアカウント一覧を表示する)
    (外部アカウント一覧を表示する)
    (外部アカウントを作成できる)
    (外部アカウントの詳細が見れる)
    (外部アカウントが削除できる)
    (外部アカウントが編集できる)
}
@enduml