@startuml 認証フロー

start
:アプリアカウントのユーザーIdとパスワードでAPIにログイン;
note left
アプリアカウントはApiへのアクセスを制限するために存在する
endnote
:ユーザーアカウントの情報を共通鍵を使ってアプリ側で認証と登録;
note left
ユーザーアカウントは共通鍵の確認と、
外部アカウントのグループ化のために存在する
endnote
:APIからの情報を共通鍵を使って複合;
stop

@enduml