export const CHANNELS = {
  WINDOW_MANAGER: {
    AUTH: "WINDOW_MANAGER/AUTH",
    MAIN: "WINDOW_MANAGER/MAIN",
    USER_ACCOUNT_MANAGER: "WINDOW_MANAGER/USER_ACCOUNT_MANAGER",
    CLOSE: "WINDOW_MANAGER/CLOSE",
  },
  ICON_SERVICE: {
    GET_FROM_URL: "ICON_SERVICE/GET_FROM_URL",
  },
};
