name: Node.js CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      # キャッシュ管理
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      # /キャッシュ管理
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build:lib
      - uses: dorny/paths-filter@v2
        id: front-changes
        with:
          filters: |
            src:
              - 'front/**'
        # run only if some file in 'src' folder was changed
        if: steps.front-changes.outputs.src == 'true'
        run: npm run test
        working-directory: ./front
      - uses: dorny/paths-filter@v2
        id: app-changes
        with:
          filters: |
            src:
              - 'app/**'
        # run only if some file in 'src' folder was changed
        if: steps.app-changes.outputs.src == 'true'
        run: npm run test
        working-directory: ./app
      - uses: dorny/paths-filter@v2
        id: lib-changes
        with:
          filters: |
            src:
              - 'lib/**'
        # run only if some file in 'src' folder was changed
        if: steps.lib-changes.outputs.src == 'true'
        run: npm run test
        working-directory: ./lib
